function opt(value,label,current){return '<option value="'+value+'" '+(String(current??'')===String(value)?'selected':'')+'>'+label+'</option>'}
function editarOs(o={}){
 $('dlgTitle').textContent=(o.id?'Editar OS ':'Novo trabalho ')+(o.os_numero||'');
 $('dlgBody').innerHTML='<form id="formOs">'+
 '<div class="sec"><h3>Identificação</h3><div class="grid3">'+
 '<div><label>OS Muby</label><input id="fOs" required value="'+esc(o.os_numero||'')+'"></div>'+
 '<div><label>Classificação N</label><select id="fN">'+opt('','Não definida',o.classificacao_n)+opt('N1','N1',o.classificacao_n)+opt('N2','N2',o.classificacao_n)+opt('N3','N3',o.classificacao_n)+opt('N4','N4',o.classificacao_n)+'</select></div>'+
 '<div><label>Ativo</label><select id="fAtivo">'+opt('true','Sim',String(o.ativo??true))+opt('false','Não',String(o.ativo??true))+'</select></div></div></div>'+
 '<div class="sec"><h3>Local</h3><div class="grid">'+
 '<div><label>Nome do local</label><input id="fLocal" value="'+esc(o.local_nome||'')+'"></div>'+
 '<div><label>Cidade</label><input id="fCidade" value="'+esc(o.local_cidade||'')+'"></div>'+
 '<div><label>CNPJ/CPF para NF transporte</label><input id="fCnpj" value="'+esc(o.local_cnpj||'')+'"></div>'+
 '<div><label>Endereço fiscal / transporte</label><input id="fEnd" value="'+esc(o.local_endereco_nf||'')+'"></div></div></div>'+
 '<div class="sec"><h3>Montagem</h3><div class="grid"><div><label>Início</label><input id="fMi" type="datetime-local" value="'+inputDate(o.montagem_inicio)+'"></div><div><label>Limite / término</label><input id="fMf" type="datetime-local" value="'+inputDate(o.montagem_fim)+'"></div></div></div>'+
 '<div class="sec"><h3>Desmontagem</h3><div class="grid3"><div><label>Existe?</label><select id="fDa">'+opt('','Não avaliado',o.desmontagem_aplica===null||o.desmontagem_aplica===undefined?'':String(o.desmontagem_aplica))+opt('true','Sim',String(o.desmontagem_aplica))+opt('false','Não',String(o.desmontagem_aplica))+'</select></div><div><label>Início</label><input id="fDi" type="datetime-local" value="'+inputDate(o.desmontagem_inicio)+'"></div><div><label>Limite</label><input id="fDf" type="datetime-local" value="'+inputDate(o.desmontagem_limite)+'"></div></div></div>'+
 '<div class="sec"><h3>Frete</h3><div class="grid3"><div><label>Precisa?</label><select id="fFp">'+opt('','Não avaliado',o.frete_precisa===null||o.frete_precisa===undefined?'':String(o.frete_precisa))+opt('true','Sim',String(o.frete_precisa))+opt('false','Não',String(o.frete_precisa))+'</select></div><div><label>Veículo / porte</label><input id="fFv" value="'+esc(o.frete_veiculo||'')+'"></div><div><label>Execução</label><select id="fFe">'+opt('','Não definido',o.frete_execucao)+opt('propria','Frota própria',o.frete_execucao)+opt('terceiro','Terceiro',o.frete_execucao)+opt('a_definir','A definir',o.frete_execucao)+'</select></div></div></div>'+
 '<div class="sec"><h3>Documentação de projeto</h3><div class="grid"><div><label>Precisa?</label><select id="fDp">'+opt('','Não avaliado',o.documentacao_projeto_precisa===null||o.documentacao_projeto_precisa===undefined?'':String(o.documentacao_projeto_precisa))+opt('true','Sim',String(o.documentacao_projeto_precisa))+opt('false','Não',String(o.documentacao_projeto_precisa))+'</select></div></div><div class="checks" style="margin-top:10px">'+
 '<label><input id="fRp" type="checkbox" '+(o.rrt_projeto?'checked':'')+'> RRT Projeto</label>'+
 '<label><input id="fRe" type="checkbox" '+(o.rrt_execucao?'checked':'')+'> RRT Execução</label>'+
 '<label><input id="fLm" type="checkbox" '+(o.laudos_m?'checked':'')+'> Laudos M</label>'+
 '<label><input id="fIg" type="checkbox" '+(o.laudo_ignifugacao?'checked':'')+'> Ignifugação</label>'+
 '<label><input id="fPe" type="checkbox" '+(o.projeto_eletrico?'checked':'')+'> Projeto elétrico</label></div></div>'+
 '<div class="sec"><h3>Acesso / SST</h3><select id="fAs">'+opt('','Não avaliado',o.acesso_sst)+opt('nomes','Somente nomes',o.acesso_sst)+opt('sst_completa','SST completa',o.acesso_sst)+opt('nao_exige','Não exige',o.acesso_sst)+'</select></div>'+
 '<div class="actions"><button>Salvar</button>'+(o.id?'<button type="button" class="ghost" id="pendBtn">Pendências</button>':'')+'</div><div id="formMsg" class="small"></div></form>';
 $('dlg').showModal();
 $('formOs').onsubmit=async e=>{e.preventDefault();const b=v=>v===''?null:v==='true';const payload={os_numero:$('fOs').value.trim(),classificacao_n:$('fN').value||null,ativo:$('fAtivo').value==='true',local_nome:$('fLocal').value.trim()||null,local_cidade:$('fCidade').value.trim()||null,local_cnpj:$('fCnpj').value.trim()||null,local_endereco_nf:$('fEnd').value.trim()||null,montagem_inicio:toIso($('fMi').value),montagem_fim:toIso($('fMf').value),desmontagem_aplica:b($('fDa').value),desmontagem_inicio:toIso($('fDi').value),desmontagem_limite:toIso($('fDf').value),frete_precisa:b($('fFp').value),frete_veiculo:$('fFv').value.trim()||null,frete_execucao:$('fFe').value||null,documentacao_projeto_precisa:b($('fDp').value),rrt_projeto:$('fRp').checked,rrt_execucao:$('fRe').checked,laudos_m:$('fLm').checked,laudo_ignifugacao:$('fIg').checked,projeto_eletrico:$('fPe').checked,acesso_sst:$('fAs').value||null,atualizado_em:new Date().toISOString()};const r=o.id?await sb.from('mural_os').update(payload).eq('id',o.id):await sb.from('mural_os').insert(payload);if(r.error){$('formMsg').textContent=r.error.message;return}$('dlg').close();carregar()};
 if(o.id)$('pendBtn').onclick=()=>editarPendencias(o);
}
function editarPendencias(o){
 const lista=pend.filter(p=>p.mural_os_id===o.id);
 $('dlgTitle').textContent='Pendências — OS '+o.os_numero;
 $('dlgBody').innerHTML='<div id="listaPend">'+(lista.length?lista.map(p=>'<div class="pend"><span class="tag">'+esc(p.tipo)+'</span><div><b>'+esc(p.descricao)+'</b><div class="small muted">'+esc(p.escopo||'')+'</div></div><span>'+fmt(p.prazo)+'</span><span>'+esc(p.responsavel||'—')+'</span><button class="ghost resolve" data-id="'+p.id+'">Resolver</button></div>').join(''):'<p class="muted">Nenhuma pendência aberta.</p>')+'</div><hr><div class="grid3"><div><label>Tipo</label><select id="pTipo"><option value="projeto">Projeto</option><option value="arquivo">Arquivo</option><option value="material">Material</option></select></div><div><label>Prazo</label><input id="pPrazo" type="datetime-local"></div><div><label>Responsável</label><input id="pResp"></div></div><div class="grid" style="margin-top:8px"><div><label>Descrição</label><input id="pDesc"></div><div><label>Escopo afetado</label><input id="pEscopo" placeholder="Ex.: item 17"></div></div><button id="addP">+ Adicionar</button>';
 document.querySelectorAll('.resolve').forEach(b=>b.onclick=async()=>{await sb.from('mural_pendencias').update({status:'resolvida',resolvido_em:new Date().toISOString()}).eq('id',Number(b.dataset.id));await carregar();editarPendencias(o)});
 $('addP').onclick=async()=>{if(!$('pDesc').value.trim())return;const r=await sb.from('mural_pendencias').insert({mural_os_id:o.id,tipo:$('pTipo').value,descricao:$('pDesc').value.trim(),escopo:$('pEscopo').value.trim()||null,prazo:toIso($('pPrazo').value),responsavel:$('pResp').value.trim()||null});if(!r.error){await carregar();editarPendencias(o)}};
}
function editarTarefa(t={}){
 $('dlgTitle').textContent=t.id?'Editar tarefa':'Nova tarefa de rua';
 $('dlgBody').innerHTML='<form id="formT"><div class="grid3"><div><label>Tipo</label><select id="tTipo">'+opt('compra','Compra',t.tipo)+opt('entrega','Entrega',t.tipo)+opt('busca','Busca',t.tipo)+opt('medicao','Medição',t.tipo)+opt('visita_tecnica','Visita técnica',t.tipo)+opt('outra','Outra',t.tipo)+'</select></div><div><label>Prazo</label><input id="tPrazo" type="datetime-local" value="'+inputDate(t.prazo)+'"></div><div><label>Responsável (opcional)</label><input id="tResp" value="'+esc(t.responsavel||'')+'"></div></div><div class="grid"><div><label>Tarefa</label><input id="tTitulo" required value="'+esc(t.titulo||'')+'"></div><div><label>Local</label><input id="tLocal" value="'+esc(t.local||'')+'"></div><div><label>OS Muby (opcional)</label><input id="tOs" value="'+esc(t.os_numero||'')+'"></div><div><label>Status</label><select id="tStatus">'+opt('aberta','Aberta',t.status||'aberta')+opt('em_andamento','Em andamento',t.status)+opt('concluida','Concluída',t.status)+opt('cancelada','Cancelada',t.status)+'</select></div></div><label>Observação</label><textarea id="tObs">'+esc(t.observacao||'')+'</textarea><br><button>Salvar tarefa</button><div id="tMsg" class="small"></div></form>';
 $('dlg').showModal();
 $('formT').onsubmit=async e=>{e.preventDefault();const p={tipo:$('tTipo').value,titulo:$('tTitulo').value.trim(),local:$('tLocal').value.trim()||null,prazo:toIso($('tPrazo').value),responsavel:$('tResp').value.trim()||null,os_numero:$('tOs').value.trim()||null,observacao:$('tObs').value.trim()||null,status:$('tStatus').value,atualizado_em:new Date().toISOString()};const r=t.id?await sb.from('mural_tarefas_rua').update(p).eq('id',t.id):await sb.from('mural_tarefas_rua').insert(p);if(r.error){$('tMsg').textContent=r.error.message;return}$('dlg').close();carregar()};
}
let timer;const refresh=()=>{clearTimeout(timer);timer=setTimeout(carregar,350)};
sb.channel('mural-admin').on('postgres_changes',{event:'*',schema:'public',table:'mural_os'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'mural_pendencias'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'mural_tarefas_rua'},refresh).subscribe();
auth();